### ISSUE TITLE
when new files are uploaded Patient data gets replaced

### ISSUE THREAD

**Issue by kachok** [amida-tech/DRE-services#9]
specifically patient name, dob gets replaced
and profile picture is removed

**Comment by chaldon** [comment]
Can't reproduce

**Comment by kachok** [comment]
@chaldon register new user "John Doe", upload bb-01.xml, Patient name will become "Isabella Jones"

**Comment by chaldon** [comment]
Hmm.... Right...
What happens is follows:

Files contains information about patient Isa Jones, parsers create record
of type Patient with this info and upload it as a part of upload process,
new Patient record overwrites whatever is in the database. Than frontend
re-read Patient record and displays a fresh version of data. So we got Isa
Jones back.

You will see that "dance" If you compare response of two URL below
http://dre2.amida-demo.com:8080/fhir/baseDstu2/Patient/alexs/_history/1
http://dre2.amida-demo.com:8080/fhir/baseDstu2/Patient/alexs/_history/2

or

http://dre2.amida-demo.com:8080/fhir/baseDstu2/Patient/alexs/_history/6
http://dre2.amida-demo.com:8080/fhir/baseDstu2/Patient/alexs/_history/7
http://dre2.amida-demo.com:8080/fhir/baseDstu2/Patient/alexs/_history/8

So this is kind of expected behavior. Do you want me to exclude Patient
record from FHIR bundle? In this case it will not be overwritten.

Regarding picture - looks like it's a bug in frontend - I check a sequence
of interactions with backend and didn't see image uploads, etc... So my
guess it's, probably a bug in frontend. They read Patient from FHIR and
forgot to pull an image from mongo.

On other hand if i update profile it will be written both in "demographis"
table on mongo and FHIR Patient, so data will be synchronized.

Thanks,
Alexey Shchelokov

cell: 240-899-5253
land: 240-449-8518
